# Use the Ruby base image
FROM ruby:3.3.0

# Set the working directory inside the container
WORKDIR /rails

# Install dependencies needed for Rails (optional)
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client xclip

# Copy Gemfile and Gemfile.lock to the container
COPY Gemfile Gemfile.lock ./

# Install Bundler and gems
RUN gem install bundler -v 2.5.18 && bundle install

RUN npm install @salesforce/cli --global


# Copy the rest of the application code
COPY . .

# Expose port 3000 for the Rails server
EXPOSE 3000

# Run the Rails server
CMD ["bash", "-c", "bundle exec rails server -b 0.0.0.0"]
