default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: ctm_development

test:
  <<: *default
  database: ctm_test
  host: test_db
  username: ctm
  password: password123

production:
  <<: *default
  database: ctm_production
  url: <%= ENV['DATABASE_URL'] %>
